# Generated by Django 4.1.7 on 2023-03-26 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApiCallHist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_type', models.IntegerField(choices=[(1, 'Chat'), (2, 'Image')])),
                ('called_dt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='WordCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(default='', max_length=100, unique=True)),
                ('unsafe_cnt', models.IntegerField(default=0)),
                ('safe_cnt', models.IntegerField(default=0)),
            ],
        ),
    ]
